version: '2'

services:
    jekyll:
        image: jekyll/builder:latest
        command: jekyll build
        volumes:
            - .:/srv/jekyll
        environment:
            - JEKYLL_ENV="production"
    nginx:
        image: nginx:alpine
        ports:
            - "8486:80"
        volumes:
            - ./_nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./_nginx/jekyll.conf:/etc/nginx/conf.d/default.conf
            - ./_site:/home/jekyll
            - ./_logs/nginx/:/var/log/nginx
        restart: always
