name: Deploy Website

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Jekyll Build
        uses: jerryjvl/jekyll-build-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::671370548051:role/github-infra-ftw-role
          aws-region: us-east-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync --delete ./_site s3://s3-chepeftw.com